"""
Django settings for sitepostakip project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wx!uc3xq-pf@f4gvggz8nd6md1(n1_n@364tdnf98di)in*yc)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'www.yenipost.com', 'yenipost.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'sitepostakip.uygpostblog',
    'rest_framework',
    'fontawesome-free',
    'django_social_share',
    'pwa',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sitepostakip.urls'

TEMPLATES=[
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }
    },
]

# Sosyal paylaşım butonu için değişiklik yapılmamış hali
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'sitepostakip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


PWA_APP_NAME = 'YeniPost'
PWA_APP_SHORT_NAME = 'YeniPost'
PWA_APP_DESCRIPTION = 'Gündemi Belirleyen Sosyal Medya Paylaşımları ve Haberler'
PWA_APP_THEME_COLOR = '#FF9400'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default' 
PWA_APP_ICONS = [ 
    {
        'src': 'static/media/icons/icon-72x72.png',
        'sizes': '72x72',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-96x96.png',
        'sizes': '96x96',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-144x144.png',
        'sizes': '144x144',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-384x384.png',
        'sizes': '384x384',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': 'static/media/icons/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'static/media/icons/icon-160x160.png',
        'sizes': '160x160',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'static/media/icons/splash.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_PREFER_RELATED_APPLICATIONS = True,
PWA_APP_RELATED_APPLICATIONS = [
    {
        'platform': 'play',
        'url': 'https://play.google.com/store/apps/details?id=com.yenipost.twa',
        'id': 'com.yenipost.twa'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'tr-TR'
