# Generated by Django 3.0.6 on 2021-10-08 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Görünümler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Görünüm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mecralar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mecra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Müşteriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Müşteri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Talepler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tal_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Talep', models.TextField()),
            ],
            options={
                'ordering': ['-Tal_Tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Profiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profil', models.TextField()),
                ('Link', models.TextField()),
                ('Bas_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Bit_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Görünüm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Görünümler')),
                ('Mecra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar')),
                ('Müşteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Müşteriler')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.TextField()),
                ('Post_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Mecra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar')),
                ('Profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Profiller')),
            ],
            options={
                'ordering': ['-Post_Tarihi'],
            },
        ),
    ]
