# Generated by Django 3.0.6 on 2021-11-29 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Görünümler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Görünüm', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Görünümler',
            },
        ),
        migrations.CreateModel(
            name='Mecralar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mecra', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mecralar',
            },
        ),
        migrations.CreateModel(
            name='Musteriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Müşteri', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Talepler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tal_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Talep', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Talepler',
                'ordering': ['-Tal_Tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Profiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profil', models.TextField()),
                ('Url', models.SlugField(unique=True)),
                ('Link', models.TextField()),
                ('Bas_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Bit_Tarihi', models.DateTimeField(default=datetime.datetime(2050, 1, 1, 0, 0))),
                ('Görünüm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Görünümler')),
                ('Mecra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar')),
                ('Müşteri', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Musteriler')),
            ],
            options={
                'verbose_name_plural': 'Profiller',
                'ordering': ['Profil'],
            },
        ),
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.TextField()),
                ('Post_Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Mecra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar')),
                ('Profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Profiller')),
            ],
            options={
                'verbose_name_plural': 'Postlar',
                'ordering': ['-Post_Tarihi'],
            },
        ),
    ]
