# Generated by Django 3.0.6 on 2020-07-29 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecralar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecra', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecra', models.TextField()),
                ('profil', models.TextField()),
                ('embed', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Talepler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep', models.TextField()),
                ('tal_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['talep'],
            },
        ),
        migrations.CreateModel(
            name='Takipler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.TextField()),
                ('link', models.TextField()),
                ('bas_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('mecra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
