# Generated by Django 3.0.6 on 2021-04-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlar',
            name='mecra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Mecralar'),
        ),
    ]
