# Generated by Django 3.0.6 on 2020-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talepler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='postlar',
            options={'ordering': ['-tarih']},
        ),
    ]
