# Generated by Django 3.0.6 on 2021-10-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0002_auto_20211009_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiller',
            options={'ordering': ['Profil']},
        ),
        migrations.AlterField(
            model_name='profiller',
            name='Bit_Tarihi',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='profiller',
            name='Görünüm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Görünümler'),
        ),
        migrations.AlterField(
            model_name='profiller',
            name='Müşteri',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='uygpostblog.Müşteriler'),
        ),
    ]
