# Generated by Django 3.0.6 on 2020-07-06 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0003_talepler_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takipler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecra', models.TextField()),
                ('profil', models.TextField()),
                ('isim', models.TextField()),
                ('link', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
