# Generated by Django 3.0.6 on 2021-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0003_auto_20211024_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Müşteriler',
            new_name='Musteriler',
        ),
        migrations.AlterModelOptions(
            name='musteriler',
            options={'verbose_name_plural': 'Müşteriler'},
        ),
    ]
