# Generated by Django 3.0.6 on 2021-11-26 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygpostblog', '0004_auto_20211126_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteriler',
            options={'verbose_name_plural': 'Müşterilers'},
        ),
        migrations.AlterField(
            model_name='profiller',
            name='Bit_Tarihi',
            field=models.TimeField(default=datetime.datetime(2050, 1, 1, 0, 0)),
        ),
    ]
